#!/usr/bin/env python3
"""Compare two evaluated NBD runs and explain F1 regressions.

This is an evaluation tool. It reads metrics/result artifacts generated by the
NBD runtime and does not contain NBD-specific business rules.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class PredictionKey:
    case_name: str
    nbd_id: str
    checkpoint_name: str
    line_anchor: str


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def compact_text(value: Any, limit: int = 180) -> str:
    text = re.sub(r"\s+", " ", str(value or "")).strip()
    if len(text) <= limit:
        return text
    return text[: limit - 3].rstrip() + "..."


def discover_case_dirs(base: Path) -> dict[str, Path]:
    metrics_files = sorted(base.glob("*/evaluation/metrics.json"))
    if (base / "evaluation" / "metrics.json").exists():
        return {base.name: base}
    return {path.parents[1].name: path.parents[1] for path in metrics_files}


def load_metrics(case_dir: Path) -> dict[str, Any]:
    return read_json(case_dir / "evaluation" / "metrics.json")


def prediction_key(case_name: str, item: dict[str, Any]) -> PredictionKey:
    return PredictionKey(
        case_name=case_name,
        nbd_id=str(item.get("nbd_id") or ""),
        checkpoint_name=str(item.get("checkpoint_name") or item.get("pred_checkpoint_name") or ""),
        line_anchor=str(item.get("line_anchor") or item.get("pred_line_anchor") or ""),
    )


def filtered_items(items: list[dict[str, Any]], nbd_ids: set[str]) -> list[dict[str, Any]]:
    if not nbd_ids:
        return items
    return [item for item in items if str(item.get("nbd_id") or "") in nbd_ids]


def false_positive_items(metrics: dict[str, Any], nbd_ids: set[str]) -> list[dict[str, Any]]:
    items = list(metrics.get("false_positives") or [])
    items.extend(metrics.get("no_line_predictions") or [])
    return filtered_items([item for item in items if isinstance(item, dict)], nbd_ids)


def match_items(metrics: dict[str, Any], nbd_ids: set[str]) -> list[dict[str, Any]]:
    return filtered_items([item for item in (metrics.get("matches") or []) if isinstance(item, dict)], nbd_ids)


def load_candidate_excerpt(case_dir: Path, nbd_id: str, line_anchor: str) -> str:
    if not nbd_id:
        return ""
    result_file = case_dir / "items" / nbd_id / "result.json"
    if not result_file.exists():
        return ""
    try:
        row = read_json(result_file)
    except json.JSONDecodeError:
        return ""
    candidates = ((row.get("model_result") or {}).get("candidates") or [])
    for candidate in candidates:
        if not isinstance(candidate, dict):
            continue
        candidate_anchor = str(candidate.get("line_anchor") or candidate.get("line") or "")
        if candidate_anchor == line_anchor:
            return compact_text(candidate.get("excerpt"))
    return compact_text((row.get("model_result") or {}).get("summary"))


def match_detail(key: PredictionKey, item: dict[str, Any]) -> dict[str, Any]:
    return {
        **asdict(key),
        "gold_line": item.get("gold_line") or item.get("line") or "",
        "name_match_type": item.get("name_match_type") or "",
        "name_match_score": item.get("name_match_score") or "",
        "source": item.get("pred_source_file") or item.get("source_file") or "",
    }


def aggregate_metric(case_metrics: list[dict[str, Any]]) -> dict[str, float]:
    gold = sum(int(item.get("gold_total") or 0) for item in case_metrics)
    ignored = sum(int(item.get("ignored_gold_total") or 0) for item in case_metrics)
    pred = sum(int(item.get("pred_total") or 0) for item in case_metrics)
    match = sum(int(item.get("match_total") or 0) for item in case_metrics)
    recall = match / gold if gold else 0.0
    precision = match / pred if pred else 0.0
    f1 = 2 * match / (gold + pred) if gold + pred else 0.0
    return {
        "gold_total": gold,
        "ignored_gold_total": ignored,
        "pred_total": pred,
        "match_total": match,
        "recall": recall,
        "precision": precision,
        "f1": f1,
    }


def format_float(value: float) -> str:
    return f"{value:.4f}"


def compare_runs(old_run: Path, new_run: Path, nbd_ids: set[str]) -> dict[str, Any]:
    old_cases = discover_case_dirs(old_run)
    new_cases = discover_case_dirs(new_run)
    case_names = sorted(set(old_cases) & set(new_cases))
    if not case_names:
        raise ValueError("未找到可对比的 case metrics.json")

    old_metrics = {name: load_metrics(old_cases[name]) for name in case_names}
    new_metrics = {name: load_metrics(new_cases[name]) for name in case_names}
    old_total = aggregate_metric(list(old_metrics.values()))
    new_total = aggregate_metric(list(new_metrics.values()))

    old_false_positive: dict[PredictionKey, dict[str, Any]] = {}
    new_false_positive: dict[PredictionKey, dict[str, Any]] = {}
    old_matches: dict[PredictionKey, dict[str, Any]] = {}
    new_matches: dict[PredictionKey, dict[str, Any]] = {}

    for name in case_names:
        for item in false_positive_items(old_metrics[name], nbd_ids):
            old_false_positive[prediction_key(name, item)] = item
        for item in false_positive_items(new_metrics[name], nbd_ids):
            new_false_positive[prediction_key(name, item)] = item
        for item in match_items(old_metrics[name], nbd_ids):
            old_matches[prediction_key(name, item)] = item
        for item in match_items(new_metrics[name], nbd_ids):
            new_matches[prediction_key(name, item)] = item

    added_fp_keys = sorted(set(new_false_positive) - set(old_false_positive), key=lambda key: (key.nbd_id, key.case_name, key.line_anchor))
    removed_fp_keys = sorted(set(old_false_positive) - set(new_false_positive), key=lambda key: (key.nbd_id, key.case_name, key.line_anchor))
    lost_match_keys = sorted(set(old_matches) - set(new_matches), key=lambda key: (key.nbd_id, key.case_name, key.line_anchor))
    gained_match_keys = sorted(set(new_matches) - set(old_matches), key=lambda key: (key.nbd_id, key.case_name, key.line_anchor))

    added_fp_by_nbd = Counter(key.nbd_id for key in added_fp_keys)
    new_fp_by_nbd = Counter(key.nbd_id for key in new_false_positive)
    old_fp_by_nbd = Counter(key.nbd_id for key in old_false_positive)
    new_match_by_nbd = Counter(key.nbd_id for key in new_matches)
    old_match_by_nbd = Counter(key.nbd_id for key in old_matches)

    added_false_positives = []
    for key in added_fp_keys:
        item = new_false_positive[key]
        added_false_positives.append(
            {
                **asdict(key),
                "excerpt": load_candidate_excerpt(new_cases[key.case_name], key.nbd_id, key.line_anchor),
                "source": item.get("pred_source_file") or item.get("source_file") or "",
            }
        )

    per_nbd = []
    all_nbd_ids = sorted(set(old_fp_by_nbd) | set(new_fp_by_nbd) | set(old_match_by_nbd) | set(new_match_by_nbd))
    for nbd_id in all_nbd_ids:
        old_match = old_match_by_nbd[nbd_id]
        new_match = new_match_by_nbd[nbd_id]
        old_fp = old_fp_by_nbd[nbd_id]
        new_fp = new_fp_by_nbd[nbd_id]
        per_nbd.append(
            {
                "nbd_id": nbd_id,
                "old_match": old_match,
                "new_match": new_match,
                "match_delta": new_match - old_match,
                "old_false_positive": old_fp,
                "new_false_positive": new_fp,
                "false_positive_delta": new_fp - old_fp,
                "old_pred": old_match + old_fp,
                "new_pred": new_match + new_fp,
                "pred_delta": (new_match + new_fp) - (old_match + old_fp),
                "added_false_positive": added_fp_by_nbd[nbd_id],
            }
        )
    per_nbd.sort(key=lambda item: (item["false_positive_delta"], item["added_false_positive"], item["pred_delta"]), reverse=True)

    return {
        "old_run": str(old_run),
        "new_run": str(new_run),
        "case_count": len(case_names),
        "nbd_filter": sorted(nbd_ids),
        "f1_dropped": new_total["f1"] < old_total["f1"],
        "old_total": old_total,
        "new_total": new_total,
        "delta": {
            key: new_total[key] - old_total[key]
            for key in ("gold_total", "ignored_gold_total", "pred_total", "match_total", "recall", "precision", "f1")
        },
        "per_nbd": per_nbd,
        "added_false_positives": added_false_positives,
        "lost_matches": [match_detail(key, old_matches[key]) for key in lost_match_keys],
        "gained_matches": [match_detail(key, new_matches[key]) for key in gained_match_keys],
        "removed_false_positive_count": len(removed_fp_keys),
        "lost_match_count": len(lost_match_keys),
        "gained_match_count": len(gained_match_keys),
    }


def render_markdown(report: dict[str, Any]) -> str:
    old_total = report["old_total"]
    new_total = report["new_total"]
    delta = report["delta"]
    lines = [
        "# F1 下降自动归因报告",
        "",
        f"- 旧 run：`{report['old_run']}`",
        f"- 新 run：`{report['new_run']}`",
        f"- 样本数：{report['case_count']}",
        f"- NBD 过滤：`{', '.join(report['nbd_filter']) if report['nbd_filter'] else '全部'}`",
        "",
        "## 1. 指标变化",
        "",
        "| 指标 | 旧 run | 新 run | 变化 |",
        "|---|---:|---:|---:|",
        f"| 匹配成功数 | {old_total['match_total']} | {new_total['match_total']} | {int(delta['match_total']):+d} |",
        f"| 工程命中输出数 | {old_total['pred_total']} | {new_total['pred_total']} | {int(delta['pred_total']):+d} |",
        f"| 召回率 | {format_float(old_total['recall'])} | {format_float(new_total['recall'])} | {delta['recall']:+.4f} |",
        f"| 精确率 | {format_float(old_total['precision'])} | {format_float(new_total['precision'])} | {delta['precision']:+.4f} |",
        f"| F1 值 | {format_float(old_total['f1'])} | {format_float(new_total['f1'])} | {delta['f1']:+.4f} |",
        "",
    ]
    if report["f1_dropped"]:
        lines.extend(
            [
                "结论：F1 下降，已自动进入误报扩散和匹配损失归因。",
                "",
            ]
        )
    else:
        lines.extend(["结论：F1 未下降。", ""])

    lines.extend(
        [
            "## 2. NBD 归因排序",
            "",
            "| NBD | 旧匹配 | 新匹配 | 匹配变化 | 旧误报 | 新误报 | 误报变化 | 新增误报 | 输出变化 |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for item in report["per_nbd"]:
        lines.append(
            f"| {item['nbd_id']} | {item['old_match']} | {item['new_match']} | {item['match_delta']:+d} | "
            f"{item['old_false_positive']} | {item['new_false_positive']} | {item['false_positive_delta']:+d} | "
            f"{item['added_false_positive']} | {item['pred_delta']:+d} |"
        )

    lines.extend(
        [
            "",
            "## 3. 新增误报明细",
            "",
            "| 样本 | NBD | 行号 | 审查点 | 原文摘录 |",
            "|---|---|---|---|---|",
        ]
    )
    for item in report["added_false_positives"][:120]:
        excerpt = str(item["excerpt"]).replace("|", "\\|")
        checkpoint_name = str(item["checkpoint_name"]).replace("|", "\\|")
        lines.append(
            f"| {item['case_name']} | {item['nbd_id']} | {item['line_anchor']} | "
            f"{checkpoint_name} | {excerpt} |"
        )
    if len(report["added_false_positives"]) > 120:
        lines.append(f"| ... | ... | ... | ... | 仅展示前 120 条，完整内容见 JSON。 |")

    lines.extend(
        [
            "",
            "## 4. 匹配损失明细",
            "",
            f"- 丢失匹配数：{report['lost_match_count']}",
            f"- 新增匹配数：{report['gained_match_count']}",
            f"- 移除误报数：{report['removed_false_positive_count']}",
            "",
            "| 样本 | NBD | 标准行号 | 原匹配行号 | 审查点 | 名称匹配 |",
            "|---|---|---:|---|---|---|",
        ]
    )
    for item in report["lost_matches"][:80]:
        checkpoint_name = str(item["checkpoint_name"]).replace("|", "\\|")
        lines.append(
            f"| {item['case_name']} | {item['nbd_id']} | {item['gold_line']} | "
            f"{item['line_anchor']} | {checkpoint_name} | {item['name_match_type']} |"
        )
    if len(report["lost_matches"]) > 80:
        lines.append("| ... | ... | ... | ... | ... | 仅展示前 80 条，完整内容见 JSON。 |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="对比两个已评测 NBD run，自动解释 F1 下降原因")
    parser.add_argument("--old-run", type=Path, required=True)
    parser.add_argument("--new-run", type=Path, required=True)
    parser.add_argument("--nbd", action="append", default=[], help="只分析指定 NBD，可重复")
    parser.add_argument("--output-dir", type=Path, help="默认写入 new-run/evaluation-comparison")
    args = parser.parse_args()

    output_dir = args.output_dir or (args.new_run / "evaluation-comparison")
    report = compare_runs(args.old_run.resolve(), args.new_run.resolve(), set(args.nbd or []))
    write_text(output_dir / "f1-regression-analysis.json", json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    write_text(output_dir / "F1下降自动归因报告.md", render_markdown(report))
    print(output_dir / "F1下降自动归因报告.md")
    print(f"f1_dropped={report['f1_dropped']}")
    print(f"old_f1={format_float(report['old_total']['f1'])} new_f1={format_float(report['new_total']['f1'])} delta={report['delta']['f1']:+.4f}")
    return 1 if report["f1_dropped"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
